server:
  port: 5000

spring:
   datasource:
      url: jdbc:postgresql://testdb.cohcqffz4gnr.ap-south-1.rds.amazonaws.com:5432/test
      username: postgres
      password: postgres
   jpa:
      hibernate:
         ddl-auto: update
         
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@10.90.1.107:1521/SIT
#    username: HR
#    password: HR
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update  